# Generated by Django 4.0 on 2024-06-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='image',
            field=models.ImageField(blank=True, default='images/group_default.png', null=True, upload_to='images/account/2024-06-08 22:00:42.226478/'),
        ),
    ]
