# Generated by Django 4.0 on 2024-06-29 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmessage_file_alter_chatroom_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='chatroom',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='chatroom',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='image',
            field=models.ImageField(blank=True, default='images/group_default.png', null=True, upload_to='images/account/2024-06-29 20:11:28.645406/'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
