# Generated by Django 4.0 on 2024-06-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='images/default_pic.png', null=True, upload_to='images/account/2024-06-08 13:35:00.599979/'),
        ),
    ]
